syntax = "proto3";

enum AxisID {
  AXIS_UNDEFINED = 0;
  AXIS_1 = 1;
  AXIS_2 = 2;
  AXIS_3 = 3;
  AXIS_4 = 4;
  AXIS_5 = 5;
  AXIS_6 = 6;
  AXIS_7 = 7;
  AXIS_8 = 8;
  AXIS_ID_MASK = 15;      // masks out the significant bits to identify the axis
  AXIS_SUBTRACTIVE = 128; // used for FunctionBase.linked_axes, treated as ADDITIVE if this bit is not set 
}

enum LogLevel {
  LOG_LEVEL_UNDEFINED = 0;
  LOG_LEVEL_DEBUG = 1;
  LOG_LEVEL_INFO = 2;
  LOG_LEVEL_WARNING = 3;
  LOG_LEVEL_ERROR = 4;
}

message LogMessage {
  // axis ID, source of this log message 
  AxisID axis_id = 1;
  // log level
  LogLevel level = 2;
  // log message
  string msg = 3;
}

message KFConstVelConfig {
  // noise scaling (divided by 255 to get a factor between 0 and 1)
  uint32 noise_scaling = 1;
}

message KFConstAccelConfig {
  // noise scaling (divided by 255 to get a factor between 0 and 1)
  uint32 noise_scaling = 1;
}

message DIYPedalKinematicConfig {
  // distance between pedal pivot and foot contact point in mm
  uint32 l_pivot_foot = 1; 
  // distance between pedal pivot and the point where the link is mounted in mm
  uint32 l_pivot_link = 2; 
  // length of the link between pedal and sled in mm
  uint32 l_link = 3; 
  // distance between pedal pivot and sled in vertical direction in mm
  uint32 l_pivot_sled_y = 4; 
  // distance between pedal pivot and sled minimum position in horizontal direction in mm
  uint32 l_pivot_sled_x_min = 5; 
  // sled stroke min to max in mm
  uint32 l_sled_stroke = 6; 
}

message AxisConfig {
  // axis ID, will be used by gateways to dispatch to the correct axis and as the ID definition for HW w/o ID DIP switches
  AxisID axis_id = 1;
  // position resolution in steps/mm
  uint32 steps_per_mm = 2;
  // polynomial coefficients for the conversion factor from load cell force to pedal force over pedal position
  repeated double coeffs_force_factor_over_contact_point_pos = 3;
  // polynomial coefficients for the conversion from contact point position to sled position
  repeated double coeffs_sled_pos_over_contact_point_pos = 4;
  // minimum absolute contact point position (0.1mm/LSB)
  int32 contact_point_pos_min_abs = 5;
  // maximum absolute contact point position (0.1mm/LSB)
  int32 contact_point_pos_max_abs = 6;
  // loadcell rating in N
  uint32 f_max_loadcell = 7;
  // invert loadcell sign
  bool b_loadcell_inverted = 8;
  // invert motor direction
  bool b_motor_inverted = 9;
  // spindle pitch in mm/rev
  uint32 mm_per_rev = 10;
  // enable ESPnow
  bool b_esp_now_enabled = 11;
  // store to EEPROM
  bool store = 12;
  // load cell filter config
  oneof load_cell_filter_config {
    KFConstVelConfig kf_const_vel = 13;
    KFConstAccelConfig kf_const_accel = 14;
  }
  // used by the Simhub Plugin to store all required kinematic parameters
  oneof kinematic_config {
    DIYPedalKinematicConfig diy_pedal = 15;
  }
}

enum ControllerAxis {
  CONTROLLER_AXIS_UNDEFINED = 0;
  CONTROLLER_AXIS_X = 1;
  CONTROLLER_AXIS_Y = 2;
  CONTROLLER_AXIS_Z = 3;
  CONTROLLER_AXIS_R_X = 4;
  CONTROLLER_AXIS_R_Y = 5;
  CONTROLLER_AXIS_R_Z = 6;
  CONTROLLER_AXIS_RUD = 7;
  CONTROLLER_AXIS_THR = 8;
  CONTROLLER_AXIS_ACC = 9;
  CONTROLLER_AXIS_BRK = 10;
  CONTROLLER_AXIS_STEER = 11;
}

enum Function {
  FUNCTION_UNDEFINED = 0;
  FUNCTION_BRAKE = 1;
  FUNCTION_ACCELERATOR = 2;
  FUNCTION_CLUTCH = 3;
  FUNCTION_FLIGHT_PEDALS = 4;
}

enum OutputMode {
  OUTPUT_MODE_FORCE = 0;
  OUTPUT_MODE_TRAVEL = 1;
}

message FunctionBase {
  // assigned function (used by Simhub plugin for internal mapping)
  Function function = 1;
  // a list of up to 4 axis IDs where the first value defines the primary axis, can be OR'ed with AXIS_SUBTRACTIVE (e.g. for a left flight pedal)
  repeated AxisID linked_axes = 2;
  // controller axis to output to
  ControllerAxis controller_output_axis = 3;
  // use force or travel as joystick output
  OutputMode output_mode = 4;
  // minimum force / position (0% up to this threshold)
  float output_min = 5;
  // maximum force / position (100% above this threshold)
  float output_max = 6;
  // store to EEPROM
  bool store = 7;
}

enum ABSPattern {
  ABS_PATTERN_UNDEFINED = 0;
  ABS_PATTERN_SINE = 1;
  ABS_PATTERN_SAWTOOTH = 2;
}

enum ABSMode {
  ABS_MODE_OFF = 0;
  ABS_MODE_FORCE = 1;
  ABS_MODE_TRAVEL = 2;
}

enum ForceDirection {
  DIRECTION_UNDEFINED = 0;
  DIRECTION_ADD = 1;
  DIRECTION_SUBTRACT = 2;
}

message SplineForceCurveConfig {
  // minimum position in mm
  int32 pos_min = 1;
  // maximum position in mm
  int32 pos_max = 2;
  // minimum force in N
  float f_min = 3;
  // maximum force in N
  float f_max = 4;
  // relative force in percent in 20% relative position increments
  repeated uint32 f_rel_points = 5;
  // cubic spline "a" parameters
  repeated float cubic_spline_params_a = 6;
  // cubic spline "b" parameters
  repeated float cubic_spline_params_b = 7;
  // force direction (DIRECTION_SUBTRACT for an automotive pedal)
  ForceDirection force_direction = 8;
}

message DamperConfig {
  // damping in positive/pressing direction in (N*s)/mm
  float positive_factor = 1;
  // damping in negative/pulling direction in (N*s)/mm
  float negative_factor = 2;
}

message ABSEffectConfig {
  // frequency in Hz
  uint32 freq = 1;
  // amplitude in N
  uint32 ampl = 2;
  // effect pattern
  ABSPattern pattern = 3;
  // mode
  ABSMode mode = 4;
  // Simulated ABS trigger level (in percent, active if > 0)
  uint32 sim_level = 5;
}

message RPMEffectConfig {
  // maximum frquency in Hz
  uint32 max_freq = 1;
  // minimum frquency in Hz
  uint32 min_freq = 2;
  // amplitude in N
  uint32 amp = 3;
}

message BitePointEffectConfig {
  // bite point effect trigger threshold
  uint32 trigger_value = 1;
  // bite point effect amplitude in N
  uint32 amp = 2;
  // bite point effect frequency in Hz
  uint32 freq = 3;
  // bite point effect enabled
  bool enabled = 4;
}

message GForceEffectConfig {
  // multiplier in percent
  uint32 multi = 1;
  // filter window width in number of samples
  uint32 window = 2;
}

message WheelSlipEffectConfig {
  // amplitude in N
  uint32 amp = 1;
  // frequency in Hz
  uint32 freq = 2;
}

message RoadImpactEffectConfig {
  // multiplier in percent
  uint32 multi = 1;
  // filter window width in number of samples
  uint32 window = 2;
}

message CustomVibrationEffectConfig {
  // amplitude in N
  uint32 amp = 1;
  // frequency in Hz
  uint32 freq = 2;
}

message AutomotivePedalConfig {
  // pedal idle (close) position in mm
  int32 pos_idle = 1;
  // pedal end (distant) position in mm
  int32 pos_end = 2;
  // force curve configuration
  SplineForceCurveConfig force_curve_config = 3;
  // damper configuration
  DamperConfig damper_config = 4;
  // ABS effect configuration
  ABSEffectConfig abs_effect_config = 5;
  // RPM effect configuration
  RPMEffectConfig rpm_effect_config = 6;
  // bite point effect configuration
  BitePointEffectConfig bp_effect_config = 7;
  // G force effect configuration
  GForceEffectConfig g_force_effect_config = 8;
  // wheel slip effect configuration
  WheelSlipEffectConfig ws_effect_config = 9;
  // Road impact effect configuration
  RoadImpactEffectConfig road_effect_config = 10;
  // Custom Vibration 1 effect configuration
  CustomVibrationEffectConfig cv_1_effect_config = 11;
  // Custom Vibration 2 effect configuration
  CustomVibrationEffectConfig cv_2_effect_config = 12;
}

message RudderBrakeConfig {
  // controller axis to output the left pedal brake value to
  ControllerAxis controller_output_axis_left_pedal = 1;
  // controller axis to output the right pedal brake value to
  ControllerAxis controller_output_axis_right_pedal = 2;
  // minimum total force for braking (0% up to this threshold)
  float f_min = 3;
  // maximum total force for braking (100% above this threshold)
  float f_max = 4;
}

message FlightPedalConfig {
   // pedal near position limit in mm
  int32 pos_near_lim = 1;
   // pedal far position limit in mm
  int32 pos_far_lim = 2;
  // damping in (N*s)/mm
  float damping = 3;
  // centering spring constant in N/mm
  float centering_spring_const = 4;
  // rudder brake config
  RudderBrakeConfig rudder_brake_config = 5;
}

message FunctionConfig {
  FunctionBase base = 1;
  oneof specific {
    AutomotivePedalConfig automotive_pedal = 2;
    FlightPedalConfig flight_pedal = 3;
  }
}

message AxisAction {
  // axis ID of the affected axis
  AxisID axis_id = 1;
  oneof action {
    bool restart = 2;
    bool enable_ota = 3;
    bool return_axis_config = 4;
    bool return_function_config = 5;
    uint32 debug_flags = 6;
  }
}

message AxisState {
  // ID of the axis this message represents
  AxisID axis_id = 1;
  // relative position
  float position = 2;
  // relative force
  float force = 3;
}

message GatewayState {
  // ESPNow RSSI, 255 = CAN
  uint32 rssi = 1;
  // one bit per axis ID, bit 0 = axis 1 
  uint32 axes_present = 2;
}

message FFBAction {
  // targeted function, will be used by gateways to dispatch to the correct axis
  Function function = 1;
  bool trigger_abs = 2;
  uint32 rpm = 3;
  uint32 g = 4;
  bool trigger_ws = 5;
  uint32 impact_value = 6;
  bool trigger_cv_1 = 7;
  bool trigger_cv_2 =8;
}

message Message {
  oneof payload {
    LogMessage log_message = 1;
    AxisConfig axis_config = 2;
    FunctionConfig function_config = 3;
    AxisAction axis_action = 4;
    AxisState axis_state = 5;
    GatewayState gateway_state = 6;
    FFBAction ffb_action = 7;
  }
}