name: PlatformIO CI

on: [push]


# see e.g. https://cgrotz.github.io/2020-08-24-esp32_ci_cd_part2/

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    
    # Prepare environment
      - uses: actions/checkout@main
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio





    # Build ESP code
      - name: Build PlatformIO Project ESP32
        working-directory: ./ESP32
        run: | 
        pio system info
        pio run --environment esp32 
        pio run --environment esp32s3usbotg
        pio run --environment esp32-speedcrafter
             
        
        
        
        
    # Publish as build artifact
      - name: Attach artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware_esp32
          path: | 
          .pio\build\esp32\firmware.bin
          .pio\build\esp32\bootloader.bin
          .pio\build\esp32\partitions.bin
        
        
        
